### ISSUE TITLE
ERROR: Invalid requirement: '../input/sacremoses'

### ISSUE THREAD

**Issue by luiscruz** [Moradnejad/Predicting-Subjective-Features-on-QA-Websites#2]
Hi! I tried to reproduce your paper but it expects a particular file `../input/sacremoses` that is not documented anywhere.
(happened while running the 2nd code cell of the notebook)

**Comment by Moradnejad** [comment]
Hi @luiscruz 

Thanks for noting that. I added a note in the Readme on where to find data.

https://www.kaggle.com/datasets/akensert/sacremoses

https://www.kaggle.com/datasets/akensert/bert-base-uncased-huggingface-transformer

https://www.kaggle.com/competitions/google-quest-challenge
